#!/usr/bin/env python3
"""Regenerate src/deployment/esp32/dtw_template_zora.h from repo data.

Enrollment: first 2 sorted clips of data/raw/custom_keywords/zora (the
pilot's rate+0 pair); threshold: suggested_threshold from
experiments/track_b/dtw_threshold.json (run calibrate_dtw_threshold.py
first); gate/cooldown: T//8 and 150 (pilot values).

  --check: verify only (exit 1 on any mismatch), do not write.
  After regenerating: python scripts/sync_firmware_headers.py --sync
"""
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
KWDIR = os.path.join(REPO, "data", "raw", "custom_keywords", "zora")
CALIB = os.path.join(REPO, "experiments", "track_b", "dtw_threshold.json")
HEADER = os.path.join(REPO, "src", "deployment", "esp32", "dtw_template_zora.h")


def build_text():
    import glob
    import soundfile as sf
    from src.features.mfcc import MFCCFeatureExtractor
    from src.dtw.templates import build_template

    clips = sorted(glob.glob(os.path.join(KWDIR, "*.wav")))[:2]
    assert len(clips) == 2, f"need 2 enroll clips in {KWDIR}"
    assert os.path.exists(CALIB), f"missing {CALIB} -- run calibrate_dtw_threshold.py first"
    mfcc = MFCCFeatureExtractor(sample_rate=16000, n_mfcc=13)
    feats = []
    for p in clips:
        a, sr = sf.read(p, dtype="float32")
        assert sr == 16000
        feats.append(mfcc.extract(a))
    tpl = build_template("zora", feats, band=8)
    thr = float(json.load(open(CALIB))["suggested_threshold"])
    t, d = tpl.frame_count, tpl.centroid.shape[1]
    flat = tpl.centroid.astype(np.float64).ravel()
    vals = ", ".join(f"{v:.8e}f" for v in flat)
    names = ", ".join(os.path.basename(p) for p in clips)
    return f"""// GENERATED by scripts/export_dtw_template.py -- DO NOT EDIT.
// Keyword: zora | enroll: {names} | threshold: EER suggestion {thr:.4f}
// Template: {t} frames x {d} MFCC (float32, {t * d * 4} B flash).
#ifndef DTW_TEMPLATE_ZORA_H_
#define DTW_TEMPLATE_ZORA_H_
#include <stdint.h>

#define DTW_ZORA_FRAMES {t}
#define DTW_ZORA_DIM {d}
#define DTW_ZORA_THRESHOLD {thr:.6f}f
#define DTW_ZORA_MIN_DURATION_FRAMES {t // 8}
#define DTW_ZORA_COOLDOWN_FRAMES 150

static const float DTW_ZORA_CENTROID[{t * d}] = {{{vals}}};

#endif  // DTW_TEMPLATE_ZORA_H_
"""


def main(argv):
    new_text = build_text()
    if "--check" in argv:
        if not os.path.exists(HEADER):
            print(f"[DTW-EXPORT] MISSING {HEADER}")
            return 1
        old = open(HEADER, encoding="utf-8").read()
        if old != new_text:
            print("[DTW-EXPORT] MISMATCH: header differs from regenerated; "
                  "run without --check, then --sync.")
            return 1
        print("[DTW-EXPORT] header matches regenerated template.")
        return 0
    open(HEADER, "w", encoding="utf-8").write(new_text)
    print(f"[DTW-EXPORT] wrote {HEADER} ({len(new_text)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
